[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Robust Testbed"
authors = [{name = "Corey", email = "ckschanker@mines.edu"}]
dynamic = ["version", "description"]
